### ISSUE TITLE
Type as binding attribute has different color

### ISSUE THREAD

**Issue by paetrik** [SAP-samples/vscode-abap-cds#2]
Is there any special reason why the "type" has different color?
![image](https://user-images.githubusercontent.com/13899394/57697316-367c7500-7653-11e9-91b0-32eb48c5ef0d.png)

**Comment by FreHu** [comment]
This is because type is also a keyword and the highlighting does not try to match the language grammar, it just recognizes some basic elements.

I can add some heuristics to avoid common names like `type`, for example "can't be followed by a colon", but I have to check that this is actually true.

**Comment by FreHu** [comment]
The latest update should handle this much better.
