### ISSUE TITLE
OData & UI Annotations

### ISSUE THREAD

**Issue by Karacraft** [SAP-samples/vscode-abap-cds#5]
This isn't a issue, i just want to know, if the extension support OData & UI annotations?
Thanks

**Comment by FreHu** [comment]
Can you give me some examples?

**Comment by Karacraft** [comment]
> Can you give me some examples?
In Eclipse, we can do this

```
@AbapCatalog.sqlViewName: 'ZCDS_MAKT_DDL'
@AbapCatalog.compiler.compareFilter: true
@AbapCatalog.preserveKey: true
@AccessControl.authorizationCheck: #CHECK
@EndUserText.label: 'MAKT ITEMS WITH MARA'
@OData.publish: true

define view ZCDS_MAKT as select from mara
left outer join makt
    on mara.matnr = makt.matnr {

    //MAKT
    @UI.lineItem: [{importance: #HIGH}, {position: 10},{label: 'Material #1'}]  
    key mara.matnr as mt1,
    @UI.lineItem: [{label: 'Material #2'}, {position: 20}]
 
}
```
But when I try this in vscode with extension, nothing shows up.

**Comment by FreHu** [comment]
Okay, so this will work, it likely just uses a file extension I was not aware of. Can you tell me what is the filename?

![](https://user-images.githubusercontent.com/5097067/94151753-0f56ca00-fe7b-11ea-9adc-ab779d1bfdae.png)

**Comment by FreHu** [comment]
Only these are currently supported https://github.com/SAP-samples/vscode-abap-cds/blob/7b93187130b3cc9ffec16bb43b68d64760eb3dda/package.json#L21-L24

**Comment by Karacraft** [comment]
> 
> 
> Okay, so this will work, it likely just uses a file extension I was not aware of. Can you tell me what is the filename?
> 
> ![](https://user-images.githubusercontent.com/5097067/94151753-0f56ca00-fe7b-11ea-9adc-ab779d1bfdae.png)

i have "asddls" extension. 
Do tell me, are these implemented as Snippets or Intellisense? cause there is no intellisense for me. Only Snippets.

Thanks

**Comment by FreHu** [comment]
I see what you're getting at now. My extension only provides snippets and syntax highlighting, it won't help you with autocompletion.
Try Marcello's https://marketplace.visualstudio.com/items?itemName=murbani.vscode-abap-remote-fs if you want to connect to a system and edit abap cds from vscode

**Comment by Karacraft** [comment]
Thanks. I'll keep this extension. It's snippets are handy too :)

**Comment by FreHu** [comment]
Actually you can't not keep it - if you install remote fs it will also install this extension as it depends on it for highlighting :)
